# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define :centos, primary: true do |centos|
    centos.vm.box = "box-cutter/centos70"
  end

  config.vm.define :ubuntu, autostart: false do |ubuntu|
    ubuntu.vm.box = "box-cutter/ubuntu1404"
  end

  config.vm.define :windows, autostart: false do |windows|
    windows.vm.box = "windows-2012R2-full-standard-eval"
    windows.vm.box_check_update = false
    windows.vm.guest = :windows
    windows.vm.communicator = :winrm

    windows.vm.provider :virtualbox do |provider, override|
      provider.gui = true
      provider.customize ['modifyvm', :id, '--ioapic', 'on'] # So we can assign multiple CPUs to the VM
      provider.customize ['modifyvm', :id, '--memory', 2048]
      provider.customize ['modifyvm', :id, '--cpus', 2]
    end

  end
end
